/*
 *  Copyright (c) 2018 by Walter Stroebel and InfComTec.
 */
package nl.infcomtec.jk8sctl.gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author walter
 */
public class EditText extends javax.swing.JFrame {

    private final StringBuilder body = new StringBuilder();
    private final File file;
    private final String title;

    /**
     * Creates new form ShowText
     *
     * @param file
     * @param text
     * @throws java.io.IOException
     */
    public EditText(File file, String text) throws IOException {
        this.file = file;
        if (null == text) {
            try (BufferedReader bfr = new BufferedReader(new FileReader(file))) {
                for (String s = bfr.readLine(); s != null; s = bfr.readLine()) {
                    body.append(s).append('\n');
                }
            }
        } else {
            body.append(text);
            if (body.length() < 1 || body.charAt(body.length() - 1) != '\n') {
                body.append('\n');
            }
        }
        this.title = file.getAbsolutePath();
        initComponents();
        setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea(body.toString());
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        butReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Text");
        setAlwaysOnTop(true);

        jta.setColumns(40);
        jta.setRows(10);
        jScrollPane1.setViewportView(jta);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jButton1.setText("Save");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        butReload.setText("Reload");
        butReload.setFocusable(false);
        butReload.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butReload.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butReloadActionPerformed(evt);
            }
        });
        jToolBar1.add(butReload);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        body.setLength(0);
        body.append(jta.getText());
        if (body.length() < 1 || body.charAt(body.length() - 1) != '\n') {
            body.append('\n');
        }
        try (FileWriter fw = new FileWriter(file)) {
            fw.write(body.toString());
        } catch (IOException ex) {
            Logger.getLogger(EditText.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butReloadActionPerformed
        jta.setText(body.toString());
    }//GEN-LAST:event_butReloadActionPerformed

    public static void showText(final File file, final String text) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditText.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new EditText(file, text).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(EditText.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butReload;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea jta;
    // End of variables declaration//GEN-END:variables
}
