/*
 *  Copyright (c) 2018 by Walter Stroebel and InfComTec.
 */
package nl.infcomtec.jk8sctl.gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import nl.infcomtec.jk8sctl.Metadata;
import nl.infcomtec.jk8sctl.RunKubeCtl;

/**
 *
 * @author walter
 */
public class KubeCtlAction extends javax.swing.JFrame {

    private String action;
    private Metadata metadata;

    /**
     * Creates new form KubeCtlAction
     */
    public KubeCtlAction(String action) {
        this.action = action;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        butOk = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        butOkClose = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        butClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KubeCtl interaction");
        setAlwaysOnTop(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText(action);
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        butOk.setText("Confirm");
        butOk.setFocusable(false);
        butOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butOk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOkActionPerformed(evt);
            }
        });
        jToolBar1.add(butOk);
        jToolBar1.add(jSeparator1);

        butOkClose.setText("Confirm and close");
        butOkClose.setToolTipText("");
        butOkClose.setFocusable(false);
        butOkClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butOkClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butOkClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butOkCloseActionPerformed(evt);
            }
        });
        jToolBar1.add(butOkClose);
        jToolBar1.add(jSeparator2);

        butClose.setText("Cancel");
        butClose.setFocusable(false);
        butClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCloseActionPerformed(evt);
            }
        });
        jToolBar1.add(butClose);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOkActionPerformed
        butOk.setEnabled(false);
        butOk.setVisible(false);
        butOkClose.setEnabled(false);
        butOkClose.setVisible(false);
        butClose.setText("Close");
        jTextArea1.setText("Running...");
        try {
            RunKubeCtl delete = RunKubeCtl.delete(metadata);
            if (delete.err.length() > 0) {
                jTextArea1.setText("Error(s):\n" + delete.err);
            } else {
                jTextArea1.setText(delete.in.toString() + "\n" + "Return status: " + delete.ret);
            }
        } catch (Exception ex) {
            Logger.getLogger(ItemSelector.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea1.setText("Exception: " + ex.toString());
        }
    }//GEN-LAST:event_butOkActionPerformed

    private void butCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCloseActionPerformed
        dispose();
    }//GEN-LAST:event_butCloseActionPerformed

    private void butOkCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butOkCloseActionPerformed
        butOk.setEnabled(false);
        butOk.setVisible(false);
        butOkClose.setEnabled(false);
        butOkClose.setVisible(false);
        butClose.setText("Close");
        new Thread() {
            @Override
            public void run() {
                try {
                    RunKubeCtl delete = RunKubeCtl.delete(metadata);
                } catch (Exception ex) {
                    Logger.getLogger(ItemSelector.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
        dispose();
    }//GEN-LAST:event_butOkCloseActionPerformed

    public static void delete(Metadata selected) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                KubeCtlAction kubeCtlAction = new KubeCtlAction("Really delete " + selected.getKind() + " in namespace " + selected.getNamespace() + " named " + selected.getName() + "?");
                kubeCtlAction.metadata = selected;
                kubeCtlAction.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butClose;
    private javax.swing.JButton butOk;
    private javax.swing.JButton butOkClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
